# Generated by Django 5.1.11 on 2025-08-16 13:11

import trakset_app.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', trakset_app.users.models.CustomUserManager()),
            ],
        ),
    ]
