# Generated by Django 5.1.11 on 2025-06-11 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(max_length=255)),
                ('type_description', models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location_name', models.CharField(max_length=255)),
                ('location_description', models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_description', models.TextField(blank=True, default="")),
                ('asset_status', models.CharField(default='available', max_length=50)),
                ('asset_serial_number', models.CharField(blank=True, max_length=100, null=True, default="")),
                ('current_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='trakset.asset_type')),
                ('asset_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='trakset.location')),
            ],
        ),
    ]
