# Generated by Django 5.1.11 on 2025-06-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_serial_number',
            new_name='serial_number',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='asset_type',
            old_name='type_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='asset_type',
            old_name='type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
    ]
