# Generated by Django 5.1.11 on 2025-06-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0003_asset_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_transfer',
            name='notes',
            field=models.TextField(blank=True, default=""),
        ),
    ]
