# Generated by Django 5.1.11 on 2025-06-12 10:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0004_asset_transfer_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asset_transfer',
            new_name='AssetTransfer',
        ),
        migrations.RenameModel(
            old_name='asset_type',
            new_name='AssetType',
        ),
    ]
