# Generated by Django 5.1.11 on 2025-06-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0007_alter_asset_location_alter_asset_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTransferNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_notes', to='trakset.assettransfernotes'),
        ),
    ]
