# Generated by Django 5.1.11 on 2025-06-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0008_assettransfernotes_alter_assettransfer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransfer',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfer', to='trakset.assettransfernotes'),
        ),
    ]
