# Generated by Django 5.1.11 on 2025-06-29 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakset', '0009_alter_assettransfer_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettransfer',
            name='notes',
        ),
        migrations.AddField(
            model_name='assettransfernotes',
            name='asset_transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='trakset.assettransfer'),
        ),
    ]
